---
name: ci


on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g
        
      - name: Install Dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - uses: actions/cache@v4
        with:
          path: |
            **/public
            **/resources
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          
      - uses: actions/setup-node@v4

      - name: Install yarn command
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Build slides
        run: |
          for slide in $(ls ./slides)
          do
             echo "########################################################"
             echo "        Build ${slide} "       
             echo "########################################################"
             yarn slidev build "slides/${slide}/slides.md" --out "../../dist/${slide}" --base "/${slide}"
          done 
          
      - name: Build index page
        run : |
          echo "###################################"
          echo "           Build Index "       
          echo "###################################"
          
          for talk in $(ls dist); 
          do
             talks="${talks}<li><a href=\"${talk}\">${talk}</a></li>"
          done
          cat << _EOF_ | tee ./dist/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <title>Talks by Maria</title>
          </head>
          <body>
          
          <div class="main">
          <h1>Talks by Maria Salcedo (WIP)</h1>
          <h2>overview</h2>
              <ul>$(echo $talks)
              </ul>
          </div>
          <br>
          <div>
            <p align="left" dir="auto">
              <a rel="nofollow me" href="https://mastodon.green/@masagu">
                <img alt="Maria's Mastodon" src="https://camo.githubusercontent.com/811f661b2b6f3e62783dd0b0456889cb7f2c6a8e145eb0d37f60453d59076579/68747470733a2f2f696d672e736869656c64732e696f2f7374617469632f76313f7374796c653d666c6174266d6573736167653d4d6173746f646f6e26636f6c6f723d363336344646266c6f676f3d6d6173746f646f6e266c6f676f436f6c6f723d7768697465266c6162656c3d" style="max-width: 100%;">
              </a>
            </p>
          <div>
          </body>
          </html>
          _EOF_

      - name: Deploy to Netlify (prod)
        if: ${{ github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' }}
        id: netlify_deploy_prod
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_TOKEN }} \
            --prod
